version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-ts-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/app/clean-ts-api/dist
      - ./package.json:/app/clean-ts-api/package.json
    ports:
      - "5050:5050"
    links:
      - mongo
